### ISSUE TITLE
Ability to change default settings for user notifications

### ISSUE THREAD

**Issue by VIRUXE** [flarum/issue-archive#329]
Pretty long title but I think it pretty much sums my request.

I ask this because I would like for my users to be notified by default whenever they are @mentioned.

Flarum is awesome. Thank for your efforts. :)

**Comment by jaredwolff** [comment]
It'd be awesome to be able to change this. My community hasn't been getting emails when I reply to their posts without explicitly following. 

Discussion here: https://community.jaredwolff.com/d/430-possible-to-get-a-discord-going

Edit: looks like this extension will fix the issue: https://extiverse.com/extension/fof/default-user-preferences It works great for new users but doesn't apply to already existing users though..

**Comment by luceos** [comment]
@jaredwolff .. I think a command might solve this. Oh look at this, I made an example for you 🪄 

https://github.com/luceos/flarum-extender-examples, see specifically the readme in that repository and:

- Command registration: https://github.com/luceos/flarum-extender-examples/blob/46588d1009f7c2c6b56974638318e3533ee4d7ea/extend.php#L17-L18
- Command class: https://github.com/luceos/flarum-extender-examples/blob/master/app/Command/DefaultUserPreferenceCommand.php

Call with `php flarum user-preference --help` eg:

```
php flarum user-preference --all 
```

The command needs a preference key and a new value. Sorry I need to go off, let me know if this works.

**Comment by jaredwolff** [comment]
@luceos you're the man. I'll give it a shot

**Comment by jaredwolff** [comment]
I feel like I'm very close:

```
# php flarum user-preference
PHP Fatal error:  Uncaught ReflectionException: Class "App\Command\DefaultUserPreferenceCommand" does not exist in /var/www/community.jaredwolff.com/vendor/illuminate/container/Container.php:877
Stack trace:
#0 /var/www/community.jaredwolff.com/vendor/illuminate/container/Container.php(877): ReflectionClass->__construct()
#1 /var/www/community.jaredwolff.com/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build()
#2 /var/www/community.jaredwolff.com/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve()
#3 /var/www/community.jaredwolff.com/vendor/flarum/core/src/Foundation/InstalledApp.php(112): Illuminate\Container\Container->make()
#4 [internal function]: Flarum\Foundation\InstalledApp->Flarum\Foundation\{closure}()
#5 /var/www/community.jaredwolff.com/vendor/flarum/core/src/Foundation/InstalledApp.php(119): array_map()
#6 /var/www/community.jaredwolff.com/vendor/flarum/core/src/Console/Server.php(36): Flarum\Foundation\InstalledApp->getConsoleCommands()
#7 /var/www/community.jaredwolff.com/flarum(24): Flarum\Console\Server->listen()
#8 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [App\Command\DefaultUserPreferenceCommand] does not exist. in /var/www/community.jaredwolff.com/vendor/illuminate/container/Container.php:879
Stack trace:
#0 /var/www/community.jaredwolff.com/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build()
#1 /var/www/community.jaredwolff.com/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve()
#2 /var/www/community.jaredwolff.com/vendor/flarum/core/src/Foundation/InstalledApp.php(112): Illuminate\Container\Container->make()
#3 [internal function]: Flarum\Foundation\InstalledApp->Flarum\Foundation\{closure}()
#4 /var/www/community.jaredwolff.com/vendor/flarum/core/src/Foundation/InstalledApp.php(119): array_map()
#5 /var/www/community.jaredwolff.com/vendor/flarum/core/src/Console/Server.php(36): Flarum\Foundation\InstalledApp->getConsoleCommands()
#6 /var/www/community.jaredwolff.com/flarum(24): Flarum\Console\Server->listen()
#7 {main}
  thrown in /var/www/community.jaredwolff.com/vendor/illuminate/container/Container.php on line 879
```

Running php 8.0 and Flarum 1.6.3

**Comment by luceos** [comment]
Make sure to read the readme, this means in your `composer.json` add the `autoload` information and run `composer dumpautoload` afterwards so that composer can resolve the Command you created in `app/Command`.

**Comment by jaredwolff** [comment]
Ahh! `composer dumpautoload` was the missing piece. May be worth a mention in the Readme. :)

**Comment by jaredwolff** [comment]
Ran these guys below.

```
php flarum user-preference --all postMentioned true
php flarum user-preference --all userMentioned true
php flarum user-preference --all followAfterReply true
```

Looked like `followAfterReply` worked. The email related ones didn't. Looking [here](https://github.com/FriendsOfFlarum/default-user-preferences/blob/614786a84e48c544cc53c630de53bf9007595f07/src/Listeners/ApplyDefaultPreferences.php) to see if I can glean anything from how it was done there.

**Comment by jaredwolff** [comment]
Found the correct format here: https://github.com/flarum/framework/blob/fc4d5e3d434c12b848e6780831c1a137c1b70ad1/framework/core/src/User/User.php#L848

Ran 

```
php flarum user-preference --all notify_postMentioned_email true
php flarum user-preference --all notify_userMentioned_email true
```

And that did  the trick! 

Thanks @luceos :smile:

**Comment by VIRUXE** [comment]
Just noticed this was still open.

@tobyzerner marked https://github.com/flarum/framework/issues/1152 as completed, with no reference commit/PR. But @jaredwolff apparently was experiencing the same "issue" a year ago.

I haven't touched Flarum in years. What would be the consensus for this now?
